import type { Metadata } from 'next';
import { Geist, Geist_Mono, Poppins, Figtree } from 'next/font/google';
import React from 'react';
import './globals.css';
import Providers from '@/app/providers';

const poppins = Poppins({
    variable: '--font-poppins',
    subsets: ['latin'],
    weight: ['300', '400', '500', '600', '700'],
});

const figtree = Figtree({
    variable: '--font-figtree',
    subsets: ['latin'],
    weight: ['300', '400', '500', '600', '700'],
});

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
    weight: ['300', '400', '500', '600', '700'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
    weight: ['300', '400', '500', '600', '700'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

const RootLayout = ({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) => {
    return (
        <html lang="en" suppressHydrationWarning>
            <body
                className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} ${figtree.variable} antialiased`}
            >
                <Providers>{children}</Providers>
            </body>
        </html>
    );
};

export default RootLayout;
